import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-auto container mx-auto h-screen bg-neutral-800 text-neutral-100`}>
        <header className='flex justify-between mb-4 py-1'>
          <Link href="/" className="text-2xl">Todos</Link>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  )
}
